# Render Blueprint Configuration for TidyFrame
# This file defines all services needed for production deployment

databases:
  - name: tidyframe-postgres
    databaseName: tidyframe
    user: tidyframe
    plan: starter # $7/month - 256MB RAM, 1GB storage
    ipAllowList: [] # Allow connections from Render services only

services:
  # Redis Cache
  - type: pserv
    name: tidyframe-redis
    runtime: docker
    dockerfilePath: ./redis.Dockerfile
    dockerContext: .
    plan: starter # $7/month - 512MB RAM
    envVars:
      - key: REDIS_MAXMEMORY
        value: 400mb
    
  # Backend API
  - type: web
    name: tidyframe-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerContext: ./backend
    plan: standard # $25/month - 2GB RAM
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tidyframe-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: tidyframe-redis
          property: hostport
      - key: FRONTEND_URL
        value: https://tidyframe.onrender.com
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_REFRESH_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: GEMINI_API_KEY
        sync: false # Must be set manually in dashboard
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: WORKERS
        value: "2"
      - key: PORT
        value: "8000"
    healthCheckPath: /api/health

  # Celery Worker
  - type: worker
    name: tidyframe-celery
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.celery
    dockerContext: ./backend
    plan: starter # $7/month - 512MB RAM
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tidyframe-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: tidyframe-redis
          property: hostport
      - key: GEMINI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: CELERY_WORKER_CONCURRENCY
        value: "1"
    
  # Celery Beat Scheduler
  - type: worker
    name: tidyframe-beat
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.beat
    dockerContext: ./backend
    plan: starter # $7/month - 512MB RAM
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tidyframe-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: tidyframe-redis
          property: hostport

  # Frontend
  - type: web
    name: tidyframe
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile.prod
    dockerContext: ./frontend
    plan: starter # $7/month - 512MB RAM
    envVars:
      - key: VITE_API_URL
        value: https://tidyframe-backend.onrender.com
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
    healthCheckPath: /

# Total estimated cost: ~$60/month
# Database: $7
# Redis: $7
# Backend: $25
# Celery Worker: $7
# Celery Beat: $7
# Frontend: $7